// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg22ufS5fj-X2ZkLxLKJVnXaSdbE6Kj2c',
    appId: '1:1092431311310:web:5ddef12a17adb915603b9f',
    messagingSenderId: '1092431311310',
    projectId: 'jamiah-riyazul',
    authDomain: 'jamiah-riyazul.firebaseapp.com',
    storageBucket: 'jamiah-riyazul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3ZY55WBWwamCDmOoyb7ubtxJdaVooVI',
    appId: '1:1092431311310:android:f5c587fbd374e4db603b9f',
    messagingSenderId: '1092431311310',
    projectId: 'jamiah-riyazul',
    storageBucket: 'jamiah-riyazul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnnNVh39Gpqm8LFp-71Mc3CNVkfK0K6o',
    appId: '1:1092431311310:ios:582dc2b479a9e243603b9f',
    messagingSenderId: '1092431311310',
    projectId: 'jamiah-riyazul',
    storageBucket: 'jamiah-riyazul.firebasestorage.app',
    iosBundleId: 'com.riyazulParent',
  );
}
